//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketPortal.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketPortal.App_LocalResources.RP", typeof(RP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action providers can be executed from here.  An action provider is designed to do a single action on the system installation, usually to update records or fix problems.
        ///&lt;br/&gt;
        ///The assembly that will be executed should be installed into the bin folder and then the correct assembly, namespace, class and extra data can be added into the fields below. &lt;br/&gt;The action provider assembly should inherit the &quot;ActionProvider&quot; class..
        /// </summary>
        internal static string actionprovider_Help {
            get {
                return ResourceManager.GetString("actionprovider.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Provider.
        /// </summary>
        internal static string actionprovider_Text {
            get {
                return ResourceManager.GetString("actionprovider.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manager.
        /// </summary>
        internal static string addmanager_Text {
            get {
                return ResourceManager.GetString("addmanager.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string assembly_Text {
            get {
                return ResourceManager.GetString("assembly.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Code.
        /// </summary>
        internal static string confirmationcode_Text {
            get {
                return ResourceManager.GetString("confirmationcode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        internal static string defaultlanguage_Text {
            get {
                return ResourceManager.GetString("defaultlanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of this service will result in the removal of ALL data linked to the service.  To continue enter the code below into the confirmation textbox..
        /// </summary>
        internal static string deleteportal_Msg {
            get {
                return ResourceManager.GetString("deleteportal.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general_Text {
            get {
                return ResourceManager.GetString("general.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Type.
        /// </summary>
        internal static string imagetype_Text {
            get {
                return ResourceManager.GetString("imagetype.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languages_Text {
            get {
                return ResourceManager.GetString("languages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Email.
        /// </summary>
        internal static string manageremail_Text {
            get {
                return ResourceManager.GetString("manageremail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Pasword.
        /// </summary>
        internal static string managerpassword_Text {
            get {
                return ResourceManager.GetString("managerpassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name_Text {
            get {
                return ResourceManager.GetString("name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.Class.
        /// </summary>
        internal static string namespaceclass_Text {
            get {
                return ResourceManager.GetString("namespaceclass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service.
        /// </summary>
        internal static string newservice_Text {
            get {
                return ResourceManager.GetString("newservice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string protocol_Text {
            get {
                return ResourceManager.GetString("protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Domain.
        /// </summary>
        internal static string rootdomain_Text {
            get {
                return ResourceManager.GetString("rootdomain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Secuirty Code is used to register a Data Client.  This code is sent by the client system to get access to this Data Service.  &lt;b&gt;KEEP THIS CODE SECRET&lt;/b&gt;.
        /// </summary>
        internal static string securitycode_Help {
            get {
                return ResourceManager.GetString("securitycode.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        internal static string securitycode_Text {
            get {
                return ResourceManager.GetString("securitycode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of Service..
        /// </summary>
        internal static string selectsystem_Text {
            get {
                return ResourceManager.GetString("selectsystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string service_Text {
            get {
                return ResourceManager.GetString("service.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL.
        /// </summary>
        internal static string serviceurl_Text {
            get {
                return ResourceManager.GetString("serviceurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system_Text {
            get {
                return ResourceManager.GetString("system.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string validate_Text {
            get {
                return ResourceManager.GetString("validate.Text", resourceCulture);
            }
        }
    }
}
