//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketPortal.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SideMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SideMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketPortal.App_LocalResources.SideMenu", typeof(SideMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Store.
        /// </summary>
        internal static string appstore_Text {
            get {
                return ResourceManager.GetString("appstore.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services.
        /// </summary>
        internal static string dashboard_Text {
            get {
                return ResourceManager.GetString("dashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Clients.
        /// </summary>
        internal static string dataclients_Text {
            get {
                return ResourceManager.GetString("dataclients.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string global_Text {
            get {
                return ResourceManager.GetString("global.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Sources.
        /// </summary>
        internal static string organisations_Text {
            get {
                return ResourceManager.GetString("organisations.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portals.
        /// </summary>
        internal static string portal_Text {
            get {
                return ResourceManager.GetString("portal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppThemes.
        /// </summary>
        internal static string rocketapptheme_Text {
            get {
                return ResourceManager.GetString("rocketapptheme.Text", resourceCulture);
            }
        }
    }
}
